version: '3.8'

services:
  web:
    build: ./apache-php
    container_name: vg_web_dev
    ports:
      - "8080:80"
    volumes:
      - ../../src:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - vgnet

  db:
    image: mariadb:10.5
    container_name: vg_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - vg_data_dev:/var/lib/mysql
    networks:
      - vgnet

volumes:
  vg_data_dev:

networks:
  vgnet:
    driver: bridge