services:
  nginx:
    image: nginx:latest
    container_name: preprod-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./php_code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - preprod_net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: preprod-php-container
    ports:
      - "9091:80"
    volumes:
      - ./php_code:/var/www/html
    depends_on:
      - db
    networks:
      - preprod_net

  db:
    image: mariadb:11
    container_name: preprod-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videgrenier
      MYSQL_USER: vguser
      MYSQL_PASSWORD: vgpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./php_code/sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - "33061:3306"
    networks:
      - preprod_net

volumes:
  db_data:

networks:
  preprod_net:
    name: preprod_net
    driver: bridge
