services:
  nginx:
    image: nginx:latest
    container_name: prod-nginx-container
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    networks:
      - prod_net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod-php-container  # ✅ moved here
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    restart: always
    env_file: "prod.env"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - prod_net

  db:
    image: mariadb:11
    container_name: prod-db-container
    restart: always
    env_file: "prod.env"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - prod_db_data:/var/lib/mysql
      - ./www/sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - "33062:3306"
    networks:
      - prod_net

volumes:
  prod_db_data:

networks:
  prod_net:
    name: prod_net
    driver: bridge
