services:
  nginx:
    image: nginx:latest
    container_name: preprod-nginx-container
    ports:
      - "8081:80"  # Preprod web on localhost:8081
    volumes:
      - ./preprod_code:/var/www/html  # Répertoire vide qui sera rempli par update_preprod_code.sh
      - ./nginx/default.preprod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    networks:
      - preprod_net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: preprod-php-container
    ports:
      - "9091:80"
    volumes:
      - ./preprod_code:/var/www/html  # Répertoire vide qui sera rempli par update_preprod_code.sh
    depends_on:
      - db
    restart: always
    env_file: "preprod.env"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - preprod_net

  db:
    image: mariadb:11
    container_name: preprod-db-container
    restart: always
    env_file: "dev.env"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - preprod_db_data:/var/lib/mysql
      - ./preprod_code/sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - "33061:3306"  # Avoid conflict with dev DB
    networks:
      - preprod_net

volumes:
  preprod_db_data:

networks:
  preprod_net:
    name: preprod_net
    driver: bridge
